### ISSUE TITLE
Collecting pmu values at regular interval

### ISSUE THREAD

**Issue by rrze-likwid** [RRZE-HPC/likwid#4] opened 2015-06-08 12:37 UTC
sursri wrote:
Is it possible to collect the event stats at a regular interval of 10 million instructions or so? I don't see the timeline function working properly for multithreaded program using perfcntr.
Is it possible to make modifications in existing likwid-perfcntr?

jan.eitzinger@fau.de:

> Please provide more details on why timeline mode does not work for threaded case.

Thomas.Roehl@fau.de:

> Since no additional information was postet by 'sursri' we cannot work on the problem with the 
> multithreaded timeline measurements.
> 
> For your first question. Yes it is possible, but there is currently no implementation of this behavior. 
> The steps are the following:
> 1. Initialize counter as normal but enable interrupt on overflow (polling would also be possible but 
> does not provide accurate results)
> 2. Set desired counter register (  Something like PMC0 with event INSTRUCTIONS_RETIRED to 
> 2^(register width) - (instruction interval)  )
> 3. Start counters
> 4. On interrupt read all configured counters and reinitialize counter registers.
> And so on.

Thomas.Roehl@fau.de:

> Not implemented in Likwid 4.0
> Likwid does not use the interrupts, so only polling possible.

**Comment by TomTheBear** [comment] 2015-10-01 14:40
I tried to implement it but the problem is, that the interrupt is only send to kernel space, not to user space. You need to say the kernel which application should be signalled. You have to use either perf_event or write an own kernel module that forwards the interrupt to likwid-perfctr.

So, from the current perspective: We will not implement this.
But we are thinking about another kernel module like (msr-safe [1] and libmsr [2]) and maybe we can integrate the interrupt stuff there.

[1] https://github.com/scalability-llnl/msr-safe
[2] https://github.com/scalability-llnl/libmsr

**Comment by TomTheBear** [comment] 2017-06-06 10:06
I'll close this issue. It doesn't seem to be implementable in user space. msr-safe is already supported but it doesn't seem to provide any functionality to use the interrupts.

**Closed by TomTheBear** 2017-06-06 10:06 UTC
