### ISSUE TITLE
NaNs and wrong event counts with MEM group on Haswell-EP and Broadwell-EP

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#142] opened 2018-02-01 12:19 UTC
Version 4.3.1, STREAM source, LIKWID markers.

```
$ likwid-perfctr -m -g MEM -C S0:0 ./a.out
[...]
+-----------------------+---------+-------------+
|         Event         | Counter |    Core 0   |
+-----------------------+---------+-------------+
|   INSTR_RETIRED_ANY   |  FIXC0  |  4725209000 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 10272400000 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |  7159699000 |
|      CAS_COUNT_RD     | MBOX0C0 |   337786500 |
|      CAS_COUNT_WR     | MBOX0C1 |   112551600 |
|      CAS_COUNT_RD     | MBOX1C0 |   337853100 |
|      CAS_COUNT_WR     | MBOX1C1 |   112629700 |
|      CAS_COUNT_RD     | MBOX2C0 |     nan     |
|      CAS_COUNT_WR     | MBOX2C1 |     nan     |
|      CAS_COUNT_RD     | MBOX3C0 |     nan     |
|      CAS_COUNT_WR     | MBOX3C1 |     nan     |
|      CAS_COUNT_RD     | MBOX4C0 |       37099 |
|      CAS_COUNT_WR     | MBOX4C1 |       17918 |
|      CAS_COUNT_RD     | MBOX5C0 |      119572 |
|      CAS_COUNT_WR     | MBOX5C1 |      100831 |
|      CAS_COUNT_RD     | MBOX6C0 |     nan     |
|      CAS_COUNT_WR     | MBOX6C1 |     nan     |
|      CAS_COUNT_RD     | MBOX7C0 |     nan     |
|      CAS_COUNT_WR     | MBOX7C1 |     nan     |
+-----------------------+---------+-------------+

```

This happens with and without markers, though. The overall traffic count appears to be OK, it's just disturbing that NaNs appear in the raw counts. One has to wonder about the significance of this.

Thanks,
Georg.

**Comment by rrzeschorscherl** [comment] 2018-02-01 13:12
PS: On a E5-2630 v4 (Broadwell 10-core in "Meggie"), the problem exists, too, but on this machine it has the bad consequence that the relevant event counts that would contribute most to the actual memory traffic are where "NaN" is reported. This means that the traffic summary (and thus the memory bandwidth reading) is off by a large factor. It severely underestimates the actual memory traffic.

**Comment by TomTheBear** [comment] 2018-02-22 13:59
With commit https://github.com/RRZE-HPC/likwid/commit/43fd56e60ef3c057a65ac0a3ae884f6a2cf24250 it prints now '-' for counters that were not measured (device not available, not readable, not writable, ...). With command line option -Z it switches back to the old behavior and prints zeros.

I tested it on "Meggie" and I cannot reproduce your problem. With previous versions of LIKWID the memory boxes MBOX0 until MBOX3 are measured and used to derive the metrics. With the current version it also measures MBOX0 until MBOX3 (MBOX5-7 are dashed, MBOX4 prints 0 because the device is present and the registers are readable/writable). So in both versions the same counters are measured and I don't see differences in the results of both versions.

likwid-4.2.1:
```
$ likwid-perfctr -C S0:0-1@S1:0-1 -m -g MEM test/streamGCC
Region triad, Group 1: MEM
[...]
|         Event         | Counter |   Core 0  |   Core 1  |  Core 10  |  Core 11  |
|      CAS_COUNT_RD     | MBOX0C0 |  24544320 |         0 |  24890900 |         0 |
|      CAS_COUNT_WR     | MBOX0C1 |   6148200 |         0 |   6255011 |         0 |
|      CAS_COUNT_RD     | MBOX1C0 |  24502660 |         0 |  24852730 |         0 |
|      CAS_COUNT_WR     | MBOX1C1 |   6159144 |         0 |   6265091 |         0 |
|      CAS_COUNT_RD     | MBOX2C0 |  24463870 |         0 |  24819180 |         0 |
|      CAS_COUNT_WR     | MBOX2C1 |   6144764 |         0 |   6250260 |         0 |
|      CAS_COUNT_RD     | MBOX3C0 |  24451350 |         0 |  24815360 |         0 |
|      CAS_COUNT_WR     | MBOX3C1 |   6139033 |         0 |   6256495 |         0 |
|      CAS_COUNT_RD     | MBOX4C0 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_WR     | MBOX4C1 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_RD     | MBOX5C0 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_WR     | MBOX5C1 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_RD     | MBOX6C0 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_WR     | MBOX6C1 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_RD     | MBOX7C0 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_WR     | MBOX7C1 |         0 |         0 |         0 |         0 |
[...]
|  Memory read bandwidth [MBytes/s] | 20885.3683 |         0 | 21228.4431 |         0 |
|  Memory read data volume [GBytes] |     6.2696 |         0 |     6.3602 |         0 |
| Memory write bandwidth [MBytes/s] |  5242.7879 |         0 |  5346.0555 |         0 |
| Memory write data volume [GBytes] |     1.5738 |         0 |     1.6017 |         0 |
|    Memory bandwidth [MBytes/s]    | 26128.1562 |         0 | 26574.4985 |         0 |
|    Memory data volume [GBytes]    |     7.8434 |         0 |     7.9619 |         0 |
```

likwid-4.3.1:
```
$ likwid-perfctr -C S0:0-1@S1:0-1 -m -g MEM test/streamGCC
Region triad, Group 1: MEM
[...]
|         Event         | Counter |   Core 0  |   Core 1  |  Core 10  |  Core 11  |
|      CAS_COUNT_RD     | MBOX0C0 |  24814920 |         0 |  24596440 |         0 |
|      CAS_COUNT_WR     | MBOX0C1 |   6308327 |         0 |   6177847 |         0 |
|      CAS_COUNT_RD     | MBOX1C0 |  24776300 |         0 |  24561080 |         0 |
|      CAS_COUNT_WR     | MBOX1C1 |   6312713 |         0 |   6191585 |         0 |
|      CAS_COUNT_RD     | MBOX2C0 |  24741780 |         0 |  24528440 |         0 |
|      CAS_COUNT_WR     | MBOX2C1 |   6285819 |         0 |   6175186 |         0 |
|      CAS_COUNT_RD     | MBOX3C0 |  24725680 |         0 |  24523230 |         0 |
|      CAS_COUNT_WR     | MBOX3C1 |   6275593 |         0 |   6173871 |         0 |
|      CAS_COUNT_RD     | MBOX4C0 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_WR     | MBOX4C1 |         0 |         0 |         0 |         0 |
|      CAS_COUNT_RD     | MBOX5C0 |     -     |     -     |     -     |     -     |
|      CAS_COUNT_WR     | MBOX5C1 |     -     |     -     |     -     |     -     |
|      CAS_COUNT_RD     | MBOX6C0 |     -     |     -     |     -     |     -     |
|      CAS_COUNT_WR     | MBOX6C1 |     -     |     -     |     -     |     -     |
|      CAS_COUNT_RD     | MBOX7C0 |     -     |     -     |     -     |     -     |
|      CAS_COUNT_WR     | MBOX7C1 |     -     |     -     |     -     |     -     |
[...]
|  Memory read bandwidth [MBytes/s] | 21121.2326 |         0 | 21014.6390 |         0 |
|  Memory read data volume [GBytes] |     6.3398 |         0 |     6.2854 |         0 |
| Memory write bandwidth [MBytes/s] |  5369.3874 |         0 |  5289.2211 |         0 |
| Memory write data volume [GBytes] |     1.6117 |         0 |     1.5820 |         0 |
|    Memory bandwidth [MBytes/s]    | 26490.6200 |         0 | 26303.8601 |         0 |
|    Memory data volume [GBytes]    |     7.9514 |         0 |     7.8674 |         0 |
```

**Comment by TomTheBear** [comment] 2018-04-20 08:59
The problem seems to be solved out, I close the issue

**Closed by TomTheBear** 2018-04-20 08:59 UTC
Labels: Events/Counters, bug
