### ISSUE TITLE
likwid-perfctr Timeline Mode Inaccuracy w/ Period < 100ms

### ISSUE THREAD

**Issue by justinborromeo** [RRZE-HPC/likwid#272] opened 2020-02-24 17:56 UTC
The docs for likwid-perfctr offer the following warning about setting the measuring period to less than 100ms:

> Notice: Although LIKWID allows measurements in a microsecond granularity, there are some points to consider. Tests have shown that for measurements below 100 milliseconds, the periodically printed results are not valid results anymore (they are higher than expected) but the behavior of the results is still valid. E.g. if you try to resolve the burst memory transfers, you need results for small intervals. The memory bandwidth for each measurement may be higher than expected (could even be higher than the theoretical maximum of the machine) but the burst and non-burst traffic is clearly identifiable by highs and lows of the memory bandwidth results.

I had some questions about these inaccuracies:
1. Do all counters provide inaccurate measurements with a short period or is it solely the memory counters?
2. Are correlations between non-memory counter measurements maintained or does the short period add an element of randomness?
3. Not sure if anyone has investigated this but has the reason behind this overestimation been identified?

**Comment by TomTheBear** [comment] 2020-02-24 18:09
Hi,
Yes, the inaccuracies affect all events but I havn't investigated deeper. We tried it once with core-local cache events (when I remember correctly on an Intel IvyBridge EP) and the correlations were the same as for memory counters. 
The problem is not clearly identified yet, but there are strong implications. If you use LIKWID in the accessdaemon mode, each access to a hardware register traverses multiple layers into the kernel and back (UNIX domain sockets, MSR driver IOCTL, ...). Every time the kernel is called, it can execute kernel-internal tasks. This adds additional overhead. Moreover, LIKWID is not using a timer interrupt (not multi-threaded) and so it calculates some sleeptime (=sleeptime_goal - read_counters_time) and uses this time. If the kernel or other stuff intercepts LIKWID and the read_counters_time > sleeptime_goal, you get a negative sleeptime. If you want to dig into it, feel free.

**Comment by justinborromeo** [comment] 2020-02-24 18:45
Would using direct access to the MSR files instead of the access daemon improve results since it'd cut down on overhead?

**Comment by TomTheBear** [comment] 2020-02-24 19:45
It might reduce the effects but you still have the switch to kernel space and back, so the delays are not predictable.
If you need samples at such a high frequency, I recommend using `perf` as it counts inside the kernel.

**Comment by justinborromeo** [comment] 2020-02-24 20:52
What's `perf`?  Is that an alternative to likwid-perfctr?

**Comment by TomTheBear** [comment] 2020-02-24 21:14
The Linux kernel provides an interface for hardware performance monitoring called `perf_event`. The user space tool to use this interface is `perf`. You can use `perf_event` also as backend of LIKWID but it does not provide all features (like no high frequency sampling).

More info: https://perf.wiki.kernel.org/index.php/Main_Page

**Comment by justinborromeo** [comment] 2020-03-07 19:14
Not sure if this is the right form to ask but is there an equivalent to Timeline Mode with perf?  I've only been able to find `perf stat` for performance counter access which outputs counter values at the end of program execution.

**Comment by TomTheBear** [comment] 2020-03-07 20:11
Look for `perf record`.

**Comment by TomTheBear** [comment] 2020-05-04 15:49
Do you have further questions/issue? Otherwise, can we close the issue?

**Closed** 2020-05-04 19:09 UTC
