### ISSUE TITLE
LIKWID-PERFCTR Cause A lot of performance loss than perf stat

### ISSUE THREAD

**Issue by Eliana-Xie** [RRZE-HPC/likwid#308] opened 2020-07-30 02:36 UTC
# TEST COMMAND
command A: likwid-perfctr -C 0-16 -g L1I_CACHE_REFILL:PMC0,L1I_CACHE:PMC1 taskset -c 0-16 APP
command B: perf stat -A -C 0-16 -e r1 -e r14 taskset -c 0-16 APP
command C: APP

# RESULT
A.APP run about  88s
B.APP run about 14s
C.APP run about 14s

likwid-perfctr cause more than 5 times performance loss
Compare to Perf Stat, It's much higher and the output of them does not have many difference

# Platform
armv8-a aarch64 、linux 4.19+

**Comment by TomTheBear** [comment] 2020-07-30 09:40
Thanks for reporting.

Yes, there are some operations before and after the execution of your application that take some time but 88s is way too high. I just tested it on an Marvell Thunder X2 and I cannot reproduce any high runtime than that.
```
$ time hostname
real	0m0.002s
user	0m0.002s
sys	0m0.000s
$ time ./likwid-perfctr -C 0 -g L2 hostname
real	0m1.852s
user	0m1.817s
sys	0m0.020s
$ time sleep 1
real	0m1.002s
user	0m0.002s
sys	0m0.001s
$ time ./likwid-perfctr -C 0 -g L2 sleep 1
real	0m2.818s
user	0m1.787s
sys	0m0.016s
```
These results indicate that likwid-perfctr add (somewhat constant) 1.8s additional (real) runtime. Most of this time is spent in initializing the timer. There is no cycle-based counter in user-space, so LIKWID on ARM8 uses `gettimeofday()` and tries to get the resolution of the timer (at least 10 times starting/stopping the counter with nanosleeps or short loops in between). I planned already to switch to the new `clock_gettime` which has a function to get the resolution. In kernel-space (perf) you can probably access a register and instantly get the time and some subsystem at boot-up has determined it's resolution. If you have an idea how to speed it up, let me know.

Just to be clear, there is no performance loss. The total runtime (wallclock) increases but your application has still the same performance as its run is not affected by neither LIKWID nor perf (not many differences in the output).

**Comment by Eliana-Xie** [comment] 2020-07-31 01:19
I test on another app sysbench, it does not cause performance losss. It appears on this small app, the app's runtime increase:
https://software.intel.com/en-us/node/624465
https://software.intel.com/sites/default/files/matrix_sample_20160413_1.tgz

**Comment by TomTheBear** [comment] 2020-08-13 13:03
I tested the Intel matrix sample and still, I cannot see any performance loss. But there is a problem with this application that might cause the confusion on your side. It always starts 16 threads, so if you do `likwid-perfctr -C 0 -g L2 ./matrix.gcc`, all 16 threads run on hardware thread 0. 

So, here is the analysis on a Marvell Thunder X2 (gcc 7.5.0):
```
$ tar -xzf matrix_sample_20160413_1.tgz
$ cd matrix_sample
$ make
$ for i in {1..10}; do taskset -c 0-15 ./matrix.gcc | grep -i "execution time"; done
Execution time = 6.884 seconds
Execution time = 5.740 seconds
Execution time = 7.526 seconds
Execution time = 7.770 seconds
Execution time = 7.339 seconds
Execution time = 5.805 seconds
Execution time = 7.403 seconds
Execution time = 6.192 seconds
Execution time = 5.959 seconds
Execution time = 6.313 seconds => min=5.74, max=7.77, avg=6.69
$ for i in {1..10}; do likwid-pin -c 0-15 ./matrix.gcc | grep -i "execution time"; done
Execution time = 6.006 seconds
Execution time = 6.037 seconds
Execution time = 6.069 seconds
Execution time = 5.917 seconds
Execution time = 5.890 seconds
Execution time = 6.109 seconds
Execution time = 5.893 seconds
Execution time = 6.011 seconds
Execution time = 6.030 seconds
Execution time = 6.001 seconds => min=5.89, max=6.11, avg=6.00
$ for i in {1..10}; do likwid-perfctr -C 0-15 -g L2 ./matrix.gcc | grep -i "execution time"; done
Execution time = 6.130 seconds
Execution time = 6.103 seconds
Execution time = 6.000 seconds
Execution time = 6.103 seconds
Execution time = 6.015 seconds
Execution time = 5.985 seconds
Execution time = 5.926 seconds
Execution time = 6.015 seconds
Execution time = 5.945 seconds
Execution time = 5.985 seconds => min=5.93, max=6.13, avg=6.02
```
So, I don't see a performance loss for the application. If you take the additionally work of likwid-perfctr into account, you might see some longer total runtime to configure/start/stop/read/evaluate the counters, setup timers and so forth as I described in may last answer.

Can you maybe specify what you mean exactly with "performance loss"?

**Comment by TomTheBear** [comment] 2020-11-09 15:49
No update? I wil close the issue soon...

**Closed** 2020-11-16 13:01 UTC
