### ISSUE TITLE
likwid-mpirun + slurm issue

### ISSUE THREAD

**Issue by mmrezaie** [RRZE-HPC/likwid#259] opened 2019-12-08 22:29 UTC
Hi,

I do have a job that runs normally using slurm's srun. I used to use perf to gather resource utilization data but I wanna use likwid-mpirun although I am getting this error:

slurmstepd: error: execve(): nil: No such file or directory

And also all the node's srun command returns error 2. I wonder where should I start looking for the problem. I am running on a Cray cluster that uses SLURM with gnu compilers.

**Comment by TomTheBear** [comment] 2019-12-09 09:46
Thanks for reporting. The issue is known and will be fixed in the next release. As workaround, use `--mpiopts ""` on the command line.

**Comment by mmrezaie** [comment] 2019-12-09 14:33
thank you. I hope I can fix this. But do you have have any particular option in mind?

**Comment by TomTheBear** [comment] 2019-12-09 15:55
I fixed this already. Closing issue.
https://github.com/RRZE-HPC/likwid/commit/265e870ecf6bfa28c4c07e7935743292d0e931ba

**Closed by TomTheBear** 2019-12-09 15:55 UTC
